version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@turbowarp/*"
      - dependency-name: "scratch-audio"
      - dependency-name: "scratch-render"
      - dependency-name: "scratch-vm"
      - dependency-name: "scratch-paint"
<<<<<<< HEAD
      - dependency-name: "scratch-blocks" 
=======
      - dependency-name: "scratch-blocks"
>>>>>>> c455eacd8a66d4b9086f751ca07e203c7ed36571
