/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Search box in sprite pane",
  "description": "Adds a search box to the sprite pane to search for sprites by name.",
  "credits": [
    {
      "name": "BarelySmooth",
      "link": "https://scratch.mit.edu/users/BarelySmooth/"
    },
    {
      "name": "GarboMuffin"
    }
  ],
  "userstyles": [
    {
      "url": "search-bar.css"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true,
  "tags": [],
<<<<<<< HEAD
  "enabledByDefault": true
=======
  "enabledByDefault": false
>>>>>>> c455eacd8a66d4b9086f751ca07e203c7ed36571
};
export default manifest;
