/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./search-bar.css";
<<<<<<< HEAD
import _asset from "!url-loader!./search-icon.svg";
import _asset2 from "!url-loader!./reset-icon.svg";
export const resources = {
  "userscript.js": _js,
  "search-bar.css": _css,
  "search-icon.svg": _asset,
  "reset-icon.svg": _asset2,
};
=======
export const resources = {
  "userscript.js": _js,
  "search-bar.css": _css,
};
>>>>>>> c455eacd8a66d4b9086f751ca07e203c7ed36571
