name: Comment on Issue Comments

on:
  issue_comment:
    types: [created]

jobs:
  post-job-comment:
    # Avoid running on comments made by bots (including itself) to prevent infinite loops
    if: ${{ !contains(github.event.comment.user.login, 'bot') }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Post comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'get a j*b <img width="640" height="854" alt="Image" src="https://github.com/user-attachments/assets/3e9896bf-da88-4e0f-8778-e66ca5e8a1ed" />'
            })
